# Generated by Django 3.1.4 on 2021-04-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('tr', models.CharField(default='', max_length=100)),
                ('en', models.CharField(default='', max_length=100)),
                ('fr', models.CharField(default='', max_length=100)),
                ('de', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('english', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('turkish', models.CharField(default='', max_length=100)),
                ('german', models.CharField(default='', max_length=100)),
                ('french', models.CharField(default='', max_length=100)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_memorization.category')),
            ],
        ),
    ]
