# Generated by Django 3.1.4 on 2021-01-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_memorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='de',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='fr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='tr',
            field=models.CharField(default='', max_length=100),
        ),
    ]
