# Generated by Django 3.1.4 on 2021-01-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_memorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
